### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by Brontojoris** [Adobe-Marketing-Cloud/aep-sdks-documentation#224]
The instructions for [Initializing the SDK](https://aep-sdks.gitbook.io/docs/getting-started/initialize-the-sdk#initializing-the-sdk) are quite confusing. The tip says:

> Tip: We recommend SDK initialization via [native code](https://github.com/adobe/react-native-acpcore) in your AppDelegate and MainApplication in iOS and Android, respectively. You may also initialize the SDK in Javascript (React Native).

The **native code** link takes the user to the React-Native implementation, which would be the opposite of what you are recommending the developer do.

Perhaps that tip could be updated to:

> Tip: We recommend SDK initialization via native code in your AppDelegate and MainApplication in iOS and Android, respectively. You may also initialize the SDK in Javascript ([React Native](https://github.com/adobe/react-native-acpcore)).

**Comment by rekrishn** [comment]
@Brontojoris, thanks for your feedback. I'll discuss your comment with the team.

**Comment by rekrishn** [comment]
the change has been made, so the issue has been closed.
