### ISSUE TITLE
Potentially Confusing Issue with ACS Android Docs

### ISSUE THREAD

**Issue by praschetan** [Adobe-Marketing-Cloud/aep-sdks-documentation#272]
Set up in-app messages and local notifications sections only have Android-specific information. Can we put these steps into iOS/Android tabs (and mark iOS as n/a) or mark the section as Android-only to avoid user confusion?

**Comment by rymorale** [comment]
I'll take a look at this. I think the suggestion of marking these sections as Android-specific information is what I'll use to resolve it.
