### ISSUE TITLE
Documentation for Visual Preview collectLaunchInfo has a potential typo

### ISSUE THREAD

**Issue by mezpahlan** [Adobe-Marketing-Cloud/aep-sdks-documentation#331]
I'm not 100% sure of the full API surface but I can't find the method `collectLaunchIInfo` as referenced in [the Android tab for VisualPreview](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-target#visual-preview).

>On Android, when the application is launched as a result of a deep link, the **collectLaunchIInfo** API is internally invoked, and the Target activity and deep link information is extracted from the Intent extras.

Looks like the change was introduced in a bigger piece about correcting the documentation so could be a simple typo that was missed [PR#220](https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/commit/c4ab7942c2c945c5a0e41f14fe1e15a8e68c6855#diff-c4cddce98a30e8e1aa5b379ca2631351R426).

I think the documentation should refer to `collectLaunchInfo` from the `MobileCore` class. Is that correct? I'm happy to raise a PR for correction if that is the case.

**Comment by praschetan** [comment]
@mezpahlan - thanks for the catch. Fixed. Cheers!
