### ISSUE TITLE
Context Data Link is Broken

### ISSUE THREAD

**Issue by robotsquidward** [Adobe-Marketing-Cloud/aep-sdks-documentation#521]
The link to learn more about 'context data' used in the Adobe Analytics Mobile Core SDK is broken. 

#### Documentation Location
https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/blob/master/foundation-extensions/mobile-core/mobile-core-api-reference.md#additional-information

#### Broken Link
https://marketing.adobe.com/resources/help/en_US/sc/implement/context_data_variables.html

Was hoping to include some documentation in my own project about how context data should be used, and would like to use the canonical source.

**Comment by praschetan** [comment]
Thanks for the catch. Docs are updated. Current link is: https://experienceleague.adobe.com/docs/analytics/implementation/vars/page-vars/contextdata.html?lang=en#vars
