### ISSUE TITLE
Broken links in getting-started/create-a-mobile-property

### ISSUE THREAD

**Issue by jasonboyer** [Adobe-Marketing-Cloud/aep-sdks-documentation#68]
There are a couple of broken links in https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property:

https://docs.adobelaunch.com/publishing/approval-workflow#library-state - 404
Should point to here possibly: https://docs.adobelaunch.com/getting-started-1/validate-and-publish#publish-to-production

https://docs.adobelaunch.com/administration/user-permissions - 404
Should point to here: https://docs.adobelaunch.com/launch-reference/administration/user-permissions

**Comment by rekrishn** [comment]
@jasonboyer, I've fixed those links and republished. Can you please check & let me know if they are correct?

Thanks.

**Comment by jasonboyer** [comment]
@rekrishn There is still a broken link to the user permissions doc in the `Additional Information` section: 
https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property#additional-information 

Bad link:
https://docs.adobelaunch.com/administration/user-permissions

**Comment by rekrishn** [comment]
Thanks @jasonboyer! Fixed that one as well.

**Comment by jasonboyer** [comment]
👍
