### ISSUE TITLE
Adobe SDKs licences

### ISSUE THREAD

**Issue by emartynov** [Adobe-Marketing-Cloud/aep-sdks-documentation#834]
Where I can find the SDKs licences?

We use cashapp licences plugin and we get next output:
```
com.adobe.marketing.mobile:analytics:2.0.1
 - ERROR: Unknown license name 'The Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:assurance:2.0.1
 - ERROR: Unknown license name 'Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:core:2.0.1
 - ERROR: Unknown license name 'The Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:identity:2.0.1
 - ERROR: Unknown license name 'The Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:lifecycle:2.0.1
 - ERROR: Unknown license name 'The Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:signal:2.0.1
 - ERROR: Unknown license name 'The Apache License, Version 2.0' with no URL is NOT allowed
com.adobe.marketing.mobile:userprofile:2.0.0
 - ERROR: Unknown license name 'Adobe Proprietary' with no URL is NOT allowed
```

The first is fixable with additional configuration of the plugin. However, we already allowed Apache license at our build the only difference I see that Adobe is not using SPDX identifier properly (hard to say without having access to the source code). You can check how kotlin team specifies licences for the own libraries.

The second error about `Adobe Proprietary` - can I read something about it? Can you specify for this library in pom like other libraries do?

**Comment by emartynov** [comment]
BTW, the user profile for iOS has Apache licences. I wonder why it is different.

**Comment by emartynov** [comment]
And for the Apache license - add the license URL, and it should work as expected.

**Comment by emartynov** [comment]
I also created tickets here:
* https://github.com/adobe/aepsdk-core-android/issues/415
* https://github.com/adobe/aepsdk-userprofile-android/issues/19

**Comment by yangyansong-adbe** [comment]
It's a duplicate issue of https://github.com/adobe/aepsdk-core-android/issues/415, close it.
